server:
  port: 80

spring:
  datasource: #数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: abc123



mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  #配置数据库下划线字段对应Java驼峰法属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id

reggie:
  upload-path: C:\Users\29566\Pictures\Reggie\
